language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - build-tools-27.0.3
    - android-27
    - sysimg-27
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-google-google_play_services
    - addon-google_apis-google-27
  licenses:
    - android-sdk-license-.+
    - android-sdk-preview-license-.+

before_install:
  # Fix Gradle output
  - export TERM=dumb
  - yes | sdkmanager "platforms;android-27"

script:
  - ./gradlew --no-daemon check -Pbuild=dev
