language: android
android:
  components:
    - tools
    - build-tools-25.0.2
    - android-25
    - sysimg-25
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-google-google_play_services
    - addon-google_apis-google-25
  licenses:
    - android-sdk-license-.+
    - android-sdk-license-.+
    - '.*intel.+'

before_install:
  # Fix Gradle output
  - export TERM=dumb

script:
  - ./gradlew check
