[versions]
activityCompose = "1.10.1"
androidImageCropper = "4.6.0"
appcompat = "1.7.0"
browser = "1.8.0"
chatkit = "5e99a8bf3c"
constraintlayoutCompose = "1.1.1"
credentialsPlayServicesAuth = "1.5.0"
espressoCore = "3.6.1"
firebaseBom = "33.13.0"
composeBom = "2025.05.00"
fragmentviewbindingdelegateKt = "1.0.2"
googleid = "1.1.1"
junit = "1.2.1"
kotlinxSerializationJson = "1.8.1"
coreKtx = "1.16.0"
lifecycleVersion = "2.9.0"
lifecycleExtensions = "2.2.0"
material = "1.12.0"
navigationFragmentKtx = "2.9.0"
okhttp = "4.12.0"
oksse = "0.9.0"
playServicesAuth = "21.3.0"
push = "6.13.0.300"
retrofit = "3.0.0"
savedstateKtx = "1.3.0"
swiperefreshlayout = "1.1.0"
truth = "1.6.0"
uiautomatorV18 = "2.1.3"
testVersion = "1.6.1"
agp = '8.10.0'
kotlin = '2.1.21'
google-services = '4.4.2'
agcp = '1.9.1.304'

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
android-image-cropper = { module = "com.vanniktech:android-image-cropper", version.ref = "androidImageCropper" }
browser = { module = "androidx.browser:browser", version.ref = "browser" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
chatkit = { module = "com.github.vitalyster:ChatKit", version.ref = "chatkit" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayoutCompose" }
converter-kotlinx-serialization = { module = "com.squareup.retrofit2:converter-kotlinx-serialization", version.ref = "retrofit" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentialsPlayServicesAuth" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
fragmentviewbindingdelegate-kt = { module = "com.github.Zhuinden:fragmentviewbindingdelegate-kt", version.ref = "fragmentviewbindingdelegateKt" }
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }
junit = { module = "androidx.test.ext:junit", version.ref = "junit" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleVersion" }
lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycleExtensions" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
material = { module = "com.google.android.material:material", version.ref = "material" }
material3 = { module = "androidx.compose.material3:material3" }
material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationFragmentKtx" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
oksse = { module = "com.github.heremaps:oksse", version.ref = "oksse" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
push = { module = "com.huawei.hms:push", version.ref = "push" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
savedstate-ktx = { module = "androidx.savedstate:savedstate-ktx", version.ref = "savedstateKtx" }
truth = { module = "androidx.test.ext:truth", version.ref = "truth" }
test-core-ktx = { module = "androidx.test:core-ktx", version.ref = "testVersion" }
ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
ui = { module = "androidx.compose.ui:ui" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
ui-viewbinding = { module = "androidx.compose.ui:ui-viewbinding" }
uiautomator-v18 = { module = "com.android.support.test.uiautomator:uiautomator-v18", version.ref = "uiautomatorV18" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-plugin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-plugin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
huawei-connect = { id = 'com.huawei.agconnect', version.ref = "agcp" }
